services:
  - type: web
    name: face-landmark-detection
    env: python
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: cd backend && uvicorn main:app --host 0.0.0.0 --port 8000
    pythonVersion: 3.11
    branch: main

