services:
  - type: web
    name: face-landmark-detection
    env: python
    region: oregon
    buildCommand: pip install -r backend/requirements.txt
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port 8000
    pythonVersion: 3.11
    branch: main


